apiVersion: v1
kind: Secret
metadata:
  name: seip-secrets
  namespace: seip
  labels:
    app.kubernetes.io/part-of: seip
type: Opaque
stringData:
  db-password: seip_secret_2024
  jwt-secret: seip-super-secret-jwt-key-2024-must-be-at-least-64-chars-long-for-hs512
  minio-access-key: seip_minio_user
  minio-secret-key: seip_minio_secret
  mail-password: changeme
  grafana-admin-password: seip_grafana_2024
